Job destcription file for wes library merge pipeline
Alexey Larionov, 31Aug2015
version 1

wecare plate3 library1 merge

===================== Analysis settings =====================

project: wecare
library: plate3_library1
lanes: lane1 lane2 lane3 lane4

Data server: admin@mgqnap.medschl.cam.ac.uk
Project location: /share/alexey/

======================= HPC settings ========================

working_folder: /scratch/medgen/users/alexey

Account to use for copying source files into HPC: TISCHKOWITZ-SL2
Max time requested for copying source files (hrs.min.sec): 02.00.00

Account to use for merging and QC: TISCHKOWITZ-SL2
Max time requested for merging and QC (hrs.min.sec): 07.00.00

Account to use for moving results out of HPC: TISCHKOWITZ-SL2
Max time requested for moving results out of HPC (hrs.min.sec): 02.00.00

====================== mgqnap settings ======================

mgqnap_user: alexey
mgqnap_group: mtgroup

==================== Pipeline summary ======================

#Pipeline merges bam files from multiple lanes for a wes library.  
#
#Then it calculated a number of metrics for the merged bam files:
#- flagstat (samtools)
#- mark-duplicates stats (picard)
#- insert sisez stats (picard)
#- alignment summary metrics (picard)
#- hybridisation selection metrics (picard)
#- Qualimap report
#- Samstat report
#
#Metrics include reports for each sample separately as well as summary 
#tables and plots for all samples on the lane. 

===================== Standard settings =====================

scripts_folder: /scratch/medgen/scripts/p02_wes_library_merge_and_qc
start_script: a00_start_pipeline.sh

Tools
-----

tools_folder: /scratch/medgen/tools

java6: java/jre1.6.0_45/bin/java
java7: java/jre1.7.0_76/bin/java
java8: java/jre1.8.0_40/bin/java

samtools: samtools/samtools-1.2/bin/samtools
samtools_folder: samtools/samtools-1.2/bin

picard: picard/picard-tools-1.133/picard.jar

r_folder: r/R-3.2.0/bin

qualimap: qualimap/qualimap_v2.1.1/qualimap.modified

gnuplot: gnuplot/gnuplot-5.0.1/bin/gnuplot
LiberationSansRegularTTF: fonts/liberation-fonts-ttf-2.00.1/LiberationSans-Regular.ttf

samstat: samstat/samstat-1.5.1/bin/samstat

rsync: rsync/rsync-3.1.1/bin/rsync

Resources
---------

resources_folder: /scratch/medgen/resources

ref_genome: gatk_bundle/b37/decompressed/human_g1k_v37.fasta

hs_metrics_probes_name: Nexera_Rapid_Capture_Exome
nextera_probes_intervals: illumina_nextera/nexterarapidcapture_exome_probes_v1.2.b37.intervals
nextera_targets_intervals: illumina_nextera/nexterarapidcapture_exome_targetedregions_v1.2.b37.intervals
nextera_targets_bed_3: illumina_nextera/nexterarapidcapture_exome_targetedregions_v1.2.b37.bed
nextera_targets_bed_6: illumina_nextera/nexterarapidcapture_exome_targetedregions_v1.2.b37.6.bed

Working sub-folders
-------------------

logs_folder: f00_logs

bam_folder: f01_bams

flagstat_folder: f02_metrics/f01_flagstat

picard_mkdup_folder: f02_metrics/f02_picard/f01_mkdup_metrics
picard_inserts_folder: f02_metrics/f02_picard/f02_inserts_metrics
picard_alignment_folder: f02_metrics/f02_picard/f03_alignment_metrics
picard_hybridisation_folder: f02_metrics/f02_picard/f04_hybridisation_metrics
picard_summary_folder: f02_metrics/f02_picard/f05_metrics_summaries

qualimap_results_folder: f02_metrics/f03_qualimap
samstat_results_folder: f02_metrics/f04_samstat
